"""empty message

Revision ID: 25114c328321
Revises: 9429d8a0cb8d
Create Date: 2019-09-26 19:29:20.025189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25114c328321'
down_revision = '9429d8a0cb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
