"""empty message

Revision ID: 9429d8a0cb8d
Revises: 0e57c3ab0581
Create Date: 2019-09-26 19:27:49.521840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9429d8a0cb8d'
down_revision = '0e57c3ab0581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
